package com.example.demo.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserAccountExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public UserAccountExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andStaffIdIsNull() {
			addCriterion("staff_id is null");
			return (Criteria) this;
		}

		public Criteria andStaffIdIsNotNull() {
			addCriterion("staff_id is not null");
			return (Criteria) this;
		}

		public Criteria andStaffIdEqualTo(String value) {
			addCriterion("staff_id =", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotEqualTo(String value) {
			addCriterion("staff_id <>", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdGreaterThan(String value) {
			addCriterion("staff_id >", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdGreaterThanOrEqualTo(String value) {
			addCriterion("staff_id >=", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdLessThan(String value) {
			addCriterion("staff_id <", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdLessThanOrEqualTo(String value) {
			addCriterion("staff_id <=", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdLike(String value) {
			addCriterion("staff_id like", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotLike(String value) {
			addCriterion("staff_id not like", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdIn(List<String> values) {
			addCriterion("staff_id in", values, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotIn(List<String> values) {
			addCriterion("staff_id not in", values, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdBetween(String value1, String value2) {
			addCriterion("staff_id between", value1, value2, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotBetween(String value1, String value2) {
			addCriterion("staff_id not between", value1, value2, "staffId");
			return (Criteria) this;
		}

		public Criteria andFullnameIsNull() {
			addCriterion("fullname is null");
			return (Criteria) this;
		}

		public Criteria andFullnameIsNotNull() {
			addCriterion("fullname is not null");
			return (Criteria) this;
		}

		public Criteria andFullnameEqualTo(String value) {
			addCriterion("fullname =", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameNotEqualTo(String value) {
			addCriterion("fullname <>", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameGreaterThan(String value) {
			addCriterion("fullname >", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameGreaterThanOrEqualTo(String value) {
			addCriterion("fullname >=", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameLessThan(String value) {
			addCriterion("fullname <", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameLessThanOrEqualTo(String value) {
			addCriterion("fullname <=", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameLike(String value) {
			addCriterion("fullname like", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameNotLike(String value) {
			addCriterion("fullname not like", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameIn(List<String> values) {
			addCriterion("fullname in", values, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameNotIn(List<String> values) {
			addCriterion("fullname not in", values, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameBetween(String value1, String value2) {
			addCriterion("fullname between", value1, value2, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameNotBetween(String value1, String value2) {
			addCriterion("fullname not between", value1, value2, "fullname");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("birthday is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("birthday is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(Date value) {
			addCriterionForJDBCDate("birthday =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(Date value) {
			addCriterionForJDBCDate("birthday <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(Date value) {
			addCriterionForJDBCDate("birthday >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("birthday >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(Date value) {
			addCriterionForJDBCDate("birthday <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("birthday <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<Date> values) {
			addCriterionForJDBCDate("birthday in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<Date> values) {
			addCriterionForJDBCDate("birthday not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("birthday between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("birthday not between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andIdCardIsNull() {
			addCriterion("id_card is null");
			return (Criteria) this;
		}

		public Criteria andIdCardIsNotNull() {
			addCriterion("id_card is not null");
			return (Criteria) this;
		}

		public Criteria andIdCardEqualTo(String value) {
			addCriterion("id_card =", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotEqualTo(String value) {
			addCriterion("id_card <>", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardGreaterThan(String value) {
			addCriterion("id_card >", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardGreaterThanOrEqualTo(String value) {
			addCriterion("id_card >=", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardLessThan(String value) {
			addCriterion("id_card <", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardLessThanOrEqualTo(String value) {
			addCriterion("id_card <=", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardLike(String value) {
			addCriterion("id_card like", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotLike(String value) {
			addCriterion("id_card not like", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardIn(List<String> values) {
			addCriterion("id_card in", values, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotIn(List<String> values) {
			addCriterion("id_card not in", values, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardBetween(String value1, String value2) {
			addCriterion("id_card between", value1, value2, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotBetween(String value1, String value2) {
			addCriterion("id_card not between", value1, value2, "idCard");
			return (Criteria) this;
		}

		public Criteria andHomePhoneIsNull() {
			addCriterion("home_phone is null");
			return (Criteria) this;
		}

		public Criteria andHomePhoneIsNotNull() {
			addCriterion("home_phone is not null");
			return (Criteria) this;
		}

		public Criteria andHomePhoneEqualTo(String value) {
			addCriterion("home_phone =", value, "homePhone");
			return (Criteria) this;
		}

		public Criteria andHomePhoneNotEqualTo(String value) {
			addCriterion("home_phone <>", value, "homePhone");
			return (Criteria) this;
		}

		public Criteria andHomePhoneGreaterThan(String value) {
			addCriterion("home_phone >", value, "homePhone");
			return (Criteria) this;
		}

		public Criteria andHomePhoneGreaterThanOrEqualTo(String value) {
			addCriterion("home_phone >=", value, "homePhone");
			return (Criteria) this;
		}

		public Criteria andHomePhoneLessThan(String value) {
			addCriterion("home_phone <", value, "homePhone");
			return (Criteria) this;
		}

		public Criteria andHomePhoneLessThanOrEqualTo(String value) {
			addCriterion("home_phone <=", value, "homePhone");
			return (Criteria) this;
		}

		public Criteria andHomePhoneLike(String value) {
			addCriterion("home_phone like", value, "homePhone");
			return (Criteria) this;
		}

		public Criteria andHomePhoneNotLike(String value) {
			addCriterion("home_phone not like", value, "homePhone");
			return (Criteria) this;
		}

		public Criteria andHomePhoneIn(List<String> values) {
			addCriterion("home_phone in", values, "homePhone");
			return (Criteria) this;
		}

		public Criteria andHomePhoneNotIn(List<String> values) {
			addCriterion("home_phone not in", values, "homePhone");
			return (Criteria) this;
		}

		public Criteria andHomePhoneBetween(String value1, String value2) {
			addCriterion("home_phone between", value1, value2, "homePhone");
			return (Criteria) this;
		}

		public Criteria andHomePhoneNotBetween(String value1, String value2) {
			addCriterion("home_phone not between", value1, value2, "homePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneIsNull() {
			addCriterion("mobile_phone is null");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneIsNotNull() {
			addCriterion("mobile_phone is not null");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneEqualTo(String value) {
			addCriterion("mobile_phone =", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneNotEqualTo(String value) {
			addCriterion("mobile_phone <>", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneGreaterThan(String value) {
			addCriterion("mobile_phone >", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneGreaterThanOrEqualTo(String value) {
			addCriterion("mobile_phone >=", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneLessThan(String value) {
			addCriterion("mobile_phone <", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneLessThanOrEqualTo(String value) {
			addCriterion("mobile_phone <=", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneLike(String value) {
			addCriterion("mobile_phone like", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneNotLike(String value) {
			addCriterion("mobile_phone not like", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneIn(List<String> values) {
			addCriterion("mobile_phone in", values, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneNotIn(List<String> values) {
			addCriterion("mobile_phone not in", values, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneBetween(String value1, String value2) {
			addCriterion("mobile_phone between", value1, value2, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneNotBetween(String value1, String value2) {
			addCriterion("mobile_phone not between", value1, value2, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNull() {
			addCriterion("role_id is null");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNotNull() {
			addCriterion("role_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoleIdEqualTo(Integer value) {
			addCriterion("role_id =", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotEqualTo(Integer value) {
			addCriterion("role_id <>", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThan(Integer value) {
			addCriterion("role_id >", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("role_id >=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThan(Integer value) {
			addCriterion("role_id <", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
			addCriterion("role_id <=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIn(List<Integer> values) {
			addCriterion("role_id in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotIn(List<Integer> values) {
			addCriterion("role_id not in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdBetween(Integer value1, Integer value2) {
			addCriterion("role_id between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
			addCriterion("role_id not between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andPositionIdIsNull() {
			addCriterion("position_id is null");
			return (Criteria) this;
		}

		public Criteria andPositionIdIsNotNull() {
			addCriterion("position_id is not null");
			return (Criteria) this;
		}

		public Criteria andPositionIdEqualTo(Long value) {
			addCriterion("position_id =", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdNotEqualTo(Long value) {
			addCriterion("position_id <>", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdGreaterThan(Long value) {
			addCriterion("position_id >", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdGreaterThanOrEqualTo(Long value) {
			addCriterion("position_id >=", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdLessThan(Long value) {
			addCriterion("position_id <", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdLessThanOrEqualTo(Long value) {
			addCriterion("position_id <=", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdIn(List<Long> values) {
			addCriterion("position_id in", values, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdNotIn(List<Long> values) {
			addCriterion("position_id not in", values, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdBetween(Long value1, Long value2) {
			addCriterion("position_id between", value1, value2, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdNotBetween(Long value1, Long value2) {
			addCriterion("position_id not between", value1, value2, "positionId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdIsNull() {
			addCriterion("department_id is null");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdIsNotNull() {
			addCriterion("department_id is not null");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdEqualTo(Long value) {
			addCriterion("department_id =", value, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdNotEqualTo(Long value) {
			addCriterion("department_id <>", value, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdGreaterThan(Long value) {
			addCriterion("department_id >", value, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdGreaterThanOrEqualTo(Long value) {
			addCriterion("department_id >=", value, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdLessThan(Long value) {
			addCriterion("department_id <", value, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdLessThanOrEqualTo(Long value) {
			addCriterion("department_id <=", value, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdIn(List<Long> values) {
			addCriterion("department_id in", values, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdNotIn(List<Long> values) {
			addCriterion("department_id not in", values, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdBetween(Long value1, Long value2) {
			addCriterion("department_id between", value1, value2, "departmentId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIdNotBetween(Long value1, Long value2) {
			addCriterion("department_id not between", value1, value2, "departmentId");
			return (Criteria) this;
		}

		public Criteria andSignaturePathIsNull() {
			addCriterion("signature_path is null");
			return (Criteria) this;
		}

		public Criteria andSignaturePathIsNotNull() {
			addCriterion("signature_path is not null");
			return (Criteria) this;
		}

		public Criteria andSignaturePathEqualTo(String value) {
			addCriterion("signature_path =", value, "signaturePath");
			return (Criteria) this;
		}

		public Criteria andSignaturePathNotEqualTo(String value) {
			addCriterion("signature_path <>", value, "signaturePath");
			return (Criteria) this;
		}

		public Criteria andSignaturePathGreaterThan(String value) {
			addCriterion("signature_path >", value, "signaturePath");
			return (Criteria) this;
		}

		public Criteria andSignaturePathGreaterThanOrEqualTo(String value) {
			addCriterion("signature_path >=", value, "signaturePath");
			return (Criteria) this;
		}

		public Criteria andSignaturePathLessThan(String value) {
			addCriterion("signature_path <", value, "signaturePath");
			return (Criteria) this;
		}

		public Criteria andSignaturePathLessThanOrEqualTo(String value) {
			addCriterion("signature_path <=", value, "signaturePath");
			return (Criteria) this;
		}

		public Criteria andSignaturePathLike(String value) {
			addCriterion("signature_path like", value, "signaturePath");
			return (Criteria) this;
		}

		public Criteria andSignaturePathNotLike(String value) {
			addCriterion("signature_path not like", value, "signaturePath");
			return (Criteria) this;
		}

		public Criteria andSignaturePathIn(List<String> values) {
			addCriterion("signature_path in", values, "signaturePath");
			return (Criteria) this;
		}

		public Criteria andSignaturePathNotIn(List<String> values) {
			addCriterion("signature_path not in", values, "signaturePath");
			return (Criteria) this;
		}

		public Criteria andSignaturePathBetween(String value1, String value2) {
			addCriterion("signature_path between", value1, value2, "signaturePath");
			return (Criteria) this;
		}

		public Criteria andSignaturePathNotBetween(String value1, String value2) {
			addCriterion("signature_path not between", value1, value2, "signaturePath");
			return (Criteria) this;
		}

		public Criteria andSignaturePassIsNull() {
			addCriterion("signature_pass is null");
			return (Criteria) this;
		}

		public Criteria andSignaturePassIsNotNull() {
			addCriterion("signature_pass is not null");
			return (Criteria) this;
		}

		public Criteria andSignaturePassEqualTo(String value) {
			addCriterion("signature_pass =", value, "signaturePass");
			return (Criteria) this;
		}

		public Criteria andSignaturePassNotEqualTo(String value) {
			addCriterion("signature_pass <>", value, "signaturePass");
			return (Criteria) this;
		}

		public Criteria andSignaturePassGreaterThan(String value) {
			addCriterion("signature_pass >", value, "signaturePass");
			return (Criteria) this;
		}

		public Criteria andSignaturePassGreaterThanOrEqualTo(String value) {
			addCriterion("signature_pass >=", value, "signaturePass");
			return (Criteria) this;
		}

		public Criteria andSignaturePassLessThan(String value) {
			addCriterion("signature_pass <", value, "signaturePass");
			return (Criteria) this;
		}

		public Criteria andSignaturePassLessThanOrEqualTo(String value) {
			addCriterion("signature_pass <=", value, "signaturePass");
			return (Criteria) this;
		}

		public Criteria andSignaturePassLike(String value) {
			addCriterion("signature_pass like", value, "signaturePass");
			return (Criteria) this;
		}

		public Criteria andSignaturePassNotLike(String value) {
			addCriterion("signature_pass not like", value, "signaturePass");
			return (Criteria) this;
		}

		public Criteria andSignaturePassIn(List<String> values) {
			addCriterion("signature_pass in", values, "signaturePass");
			return (Criteria) this;
		}

		public Criteria andSignaturePassNotIn(List<String> values) {
			addCriterion("signature_pass not in", values, "signaturePass");
			return (Criteria) this;
		}

		public Criteria andSignaturePassBetween(String value1, String value2) {
			addCriterion("signature_pass between", value1, value2, "signaturePass");
			return (Criteria) this;
		}

		public Criteria andSignaturePassNotBetween(String value1, String value2) {
			addCriterion("signature_pass not between", value1, value2, "signaturePass");
			return (Criteria) this;
		}

		public Criteria andDoctorTypeIsNull() {
			addCriterion("doctor_type is null");
			return (Criteria) this;
		}

		public Criteria andDoctorTypeIsNotNull() {
			addCriterion("doctor_type is not null");
			return (Criteria) this;
		}

		public Criteria andDoctorTypeEqualTo(Boolean value) {
			addCriterion("doctor_type =", value, "doctorType");
			return (Criteria) this;
		}

		public Criteria andDoctorTypeNotEqualTo(Boolean value) {
			addCriterion("doctor_type <>", value, "doctorType");
			return (Criteria) this;
		}

		public Criteria andDoctorTypeGreaterThan(Boolean value) {
			addCriterion("doctor_type >", value, "doctorType");
			return (Criteria) this;
		}

		public Criteria andDoctorTypeGreaterThanOrEqualTo(Boolean value) {
			addCriterion("doctor_type >=", value, "doctorType");
			return (Criteria) this;
		}

		public Criteria andDoctorTypeLessThan(Boolean value) {
			addCriterion("doctor_type <", value, "doctorType");
			return (Criteria) this;
		}

		public Criteria andDoctorTypeLessThanOrEqualTo(Boolean value) {
			addCriterion("doctor_type <=", value, "doctorType");
			return (Criteria) this;
		}

		public Criteria andDoctorTypeIn(List<Boolean> values) {
			addCriterion("doctor_type in", values, "doctorType");
			return (Criteria) this;
		}

		public Criteria andDoctorTypeNotIn(List<Boolean> values) {
			addCriterion("doctor_type not in", values, "doctorType");
			return (Criteria) this;
		}

		public Criteria andDoctorTypeBetween(Boolean value1, Boolean value2) {
			addCriterion("doctor_type between", value1, value2, "doctorType");
			return (Criteria) this;
		}

		public Criteria andDoctorTypeNotBetween(Boolean value1, Boolean value2) {
			addCriterion("doctor_type not between", value1, value2, "doctorType");
			return (Criteria) this;
		}

		public Criteria andAllowRemoteAccessIsNull() {
			addCriterion("allow_remote_access is null");
			return (Criteria) this;
		}

		public Criteria andAllowRemoteAccessIsNotNull() {
			addCriterion("allow_remote_access is not null");
			return (Criteria) this;
		}

		public Criteria andAllowRemoteAccessEqualTo(Boolean value) {
			addCriterion("allow_remote_access =", value, "allowRemoteAccess");
			return (Criteria) this;
		}

		public Criteria andAllowRemoteAccessNotEqualTo(Boolean value) {
			addCriterion("allow_remote_access <>", value, "allowRemoteAccess");
			return (Criteria) this;
		}

		public Criteria andAllowRemoteAccessGreaterThan(Boolean value) {
			addCriterion("allow_remote_access >", value, "allowRemoteAccess");
			return (Criteria) this;
		}

		public Criteria andAllowRemoteAccessGreaterThanOrEqualTo(Boolean value) {
			addCriterion("allow_remote_access >=", value, "allowRemoteAccess");
			return (Criteria) this;
		}

		public Criteria andAllowRemoteAccessLessThan(Boolean value) {
			addCriterion("allow_remote_access <", value, "allowRemoteAccess");
			return (Criteria) this;
		}

		public Criteria andAllowRemoteAccessLessThanOrEqualTo(Boolean value) {
			addCriterion("allow_remote_access <=", value, "allowRemoteAccess");
			return (Criteria) this;
		}

		public Criteria andAllowRemoteAccessIn(List<Boolean> values) {
			addCriterion("allow_remote_access in", values, "allowRemoteAccess");
			return (Criteria) this;
		}

		public Criteria andAllowRemoteAccessNotIn(List<Boolean> values) {
			addCriterion("allow_remote_access not in", values, "allowRemoteAccess");
			return (Criteria) this;
		}

		public Criteria andAllowRemoteAccessBetween(Boolean value1, Boolean value2) {
			addCriterion("allow_remote_access between", value1, value2, "allowRemoteAccess");
			return (Criteria) this;
		}

		public Criteria andAllowRemoteAccessNotBetween(Boolean value1, Boolean value2) {
			addCriterion("allow_remote_access not between", value1, value2, "allowRemoteAccess");
			return (Criteria) this;
		}

		public Criteria andIsLockIsNull() {
			addCriterion("is_lock is null");
			return (Criteria) this;
		}

		public Criteria andIsLockIsNotNull() {
			addCriterion("is_lock is not null");
			return (Criteria) this;
		}

		public Criteria andIsLockEqualTo(Boolean value) {
			addCriterion("is_lock =", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockNotEqualTo(Boolean value) {
			addCriterion("is_lock <>", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockGreaterThan(Boolean value) {
			addCriterion("is_lock >", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_lock >=", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockLessThan(Boolean value) {
			addCriterion("is_lock <", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockLessThanOrEqualTo(Boolean value) {
			addCriterion("is_lock <=", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockIn(List<Boolean> values) {
			addCriterion("is_lock in", values, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockNotIn(List<Boolean> values) {
			addCriterion("is_lock not in", values, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockBetween(Boolean value1, Boolean value2) {
			addCriterion("is_lock between", value1, value2, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_lock not between", value1, value2, "isLock");
			return (Criteria) this;
		}

		public Criteria andUserTypeIsNull() {
			addCriterion("user_type is null");
			return (Criteria) this;
		}

		public Criteria andUserTypeIsNotNull() {
			addCriterion("user_type is not null");
			return (Criteria) this;
		}

		public Criteria andUserTypeEqualTo(Boolean value) {
			addCriterion("user_type =", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotEqualTo(Boolean value) {
			addCriterion("user_type <>", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeGreaterThan(Boolean value) {
			addCriterion("user_type >", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeGreaterThanOrEqualTo(Boolean value) {
			addCriterion("user_type >=", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeLessThan(Boolean value) {
			addCriterion("user_type <", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeLessThanOrEqualTo(Boolean value) {
			addCriterion("user_type <=", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeIn(List<Boolean> values) {
			addCriterion("user_type in", values, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotIn(List<Boolean> values) {
			addCriterion("user_type not in", values, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeBetween(Boolean value1, Boolean value2) {
			addCriterion("user_type between", value1, value2, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotBetween(Boolean value1, Boolean value2) {
			addCriterion("user_type not between", value1, value2, "userType");
			return (Criteria) this;
		}

		public Criteria andIsPartnerIsNull() {
			addCriterion("is_partner is null");
			return (Criteria) this;
		}

		public Criteria andIsPartnerIsNotNull() {
			addCriterion("is_partner is not null");
			return (Criteria) this;
		}

		public Criteria andIsPartnerEqualTo(Boolean value) {
			addCriterion("is_partner =", value, "isPartner");
			return (Criteria) this;
		}

		public Criteria andIsPartnerNotEqualTo(Boolean value) {
			addCriterion("is_partner <>", value, "isPartner");
			return (Criteria) this;
		}

		public Criteria andIsPartnerGreaterThan(Boolean value) {
			addCriterion("is_partner >", value, "isPartner");
			return (Criteria) this;
		}

		public Criteria andIsPartnerGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_partner >=", value, "isPartner");
			return (Criteria) this;
		}

		public Criteria andIsPartnerLessThan(Boolean value) {
			addCriterion("is_partner <", value, "isPartner");
			return (Criteria) this;
		}

		public Criteria andIsPartnerLessThanOrEqualTo(Boolean value) {
			addCriterion("is_partner <=", value, "isPartner");
			return (Criteria) this;
		}

		public Criteria andIsPartnerIn(List<Boolean> values) {
			addCriterion("is_partner in", values, "isPartner");
			return (Criteria) this;
		}

		public Criteria andIsPartnerNotIn(List<Boolean> values) {
			addCriterion("is_partner not in", values, "isPartner");
			return (Criteria) this;
		}

		public Criteria andIsPartnerBetween(Boolean value1, Boolean value2) {
			addCriterion("is_partner between", value1, value2, "isPartner");
			return (Criteria) this;
		}

		public Criteria andIsPartnerNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_partner not between", value1, value2, "isPartner");
			return (Criteria) this;
		}

		public Criteria andHeadquarterIdIsNull() {
			addCriterion("headquarter_id is null");
			return (Criteria) this;
		}

		public Criteria andHeadquarterIdIsNotNull() {
			addCriterion("headquarter_id is not null");
			return (Criteria) this;
		}

		public Criteria andHeadquarterIdEqualTo(Long value) {
			addCriterion("headquarter_id =", value, "headquarterId");
			return (Criteria) this;
		}

		public Criteria andHeadquarterIdNotEqualTo(Long value) {
			addCriterion("headquarter_id <>", value, "headquarterId");
			return (Criteria) this;
		}

		public Criteria andHeadquarterIdGreaterThan(Long value) {
			addCriterion("headquarter_id >", value, "headquarterId");
			return (Criteria) this;
		}

		public Criteria andHeadquarterIdGreaterThanOrEqualTo(Long value) {
			addCriterion("headquarter_id >=", value, "headquarterId");
			return (Criteria) this;
		}

		public Criteria andHeadquarterIdLessThan(Long value) {
			addCriterion("headquarter_id <", value, "headquarterId");
			return (Criteria) this;
		}

		public Criteria andHeadquarterIdLessThanOrEqualTo(Long value) {
			addCriterion("headquarter_id <=", value, "headquarterId");
			return (Criteria) this;
		}

		public Criteria andHeadquarterIdIn(List<Long> values) {
			addCriterion("headquarter_id in", values, "headquarterId");
			return (Criteria) this;
		}

		public Criteria andHeadquarterIdNotIn(List<Long> values) {
			addCriterion("headquarter_id not in", values, "headquarterId");
			return (Criteria) this;
		}

		public Criteria andHeadquarterIdBetween(Long value1, Long value2) {
			addCriterion("headquarter_id between", value1, value2, "headquarterId");
			return (Criteria) this;
		}

		public Criteria andHeadquarterIdNotBetween(Long value1, Long value2) {
			addCriterion("headquarter_id not between", value1, value2, "headquarterId");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListIsNull() {
			addCriterion("headquarter_list is null");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListIsNotNull() {
			addCriterion("headquarter_list is not null");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListEqualTo(String value) {
			addCriterion("headquarter_list =", value, "headquarterList");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListNotEqualTo(String value) {
			addCriterion("headquarter_list <>", value, "headquarterList");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListGreaterThan(String value) {
			addCriterion("headquarter_list >", value, "headquarterList");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListGreaterThanOrEqualTo(String value) {
			addCriterion("headquarter_list >=", value, "headquarterList");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListLessThan(String value) {
			addCriterion("headquarter_list <", value, "headquarterList");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListLessThanOrEqualTo(String value) {
			addCriterion("headquarter_list <=", value, "headquarterList");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListLike(String value) {
			addCriterion("headquarter_list like", value, "headquarterList");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListNotLike(String value) {
			addCriterion("headquarter_list not like", value, "headquarterList");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListIn(List<String> values) {
			addCriterion("headquarter_list in", values, "headquarterList");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListNotIn(List<String> values) {
			addCriterion("headquarter_list not in", values, "headquarterList");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListBetween(String value1, String value2) {
			addCriterion("headquarter_list between", value1, value2, "headquarterList");
			return (Criteria) this;
		}

		public Criteria andHeadquarterListNotBetween(String value1, String value2) {
			addCriterion("headquarter_list not between", value1, value2, "headquarterList");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNull() {
			addCriterion("create_by is null");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNotNull() {
			addCriterion("create_by is not null");
			return (Criteria) this;
		}

		public Criteria andCreateByEqualTo(String value) {
			addCriterion("create_by =", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotEqualTo(String value) {
			addCriterion("create_by <>", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThan(String value) {
			addCriterion("create_by >", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThanOrEqualTo(String value) {
			addCriterion("create_by >=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThan(String value) {
			addCriterion("create_by <", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThanOrEqualTo(String value) {
			addCriterion("create_by <=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLike(String value) {
			addCriterion("create_by like", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotLike(String value) {
			addCriterion("create_by not like", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByIn(List<String> values) {
			addCriterion("create_by in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotIn(List<String> values) {
			addCriterion("create_by not in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByBetween(String value1, String value2) {
			addCriterion("create_by between", value1, value2, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotBetween(String value1, String value2) {
			addCriterion("create_by not between", value1, value2, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andUpdateByIsNull() {
			addCriterion("update_by is null");
			return (Criteria) this;
		}

		public Criteria andUpdateByIsNotNull() {
			addCriterion("update_by is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateByEqualTo(String value) {
			addCriterion("update_by =", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotEqualTo(String value) {
			addCriterion("update_by <>", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByGreaterThan(String value) {
			addCriterion("update_by >", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
			addCriterion("update_by >=", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByLessThan(String value) {
			addCriterion("update_by <", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByLessThanOrEqualTo(String value) {
			addCriterion("update_by <=", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByLike(String value) {
			addCriterion("update_by like", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotLike(String value) {
			addCriterion("update_by not like", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByIn(List<String> values) {
			addCriterion("update_by in", values, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotIn(List<String> values) {
			addCriterion("update_by not in", values, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByBetween(String value1, String value2) {
			addCriterion("update_by between", value1, value2, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotBetween(String value1, String value2) {
			addCriterion("update_by not between", value1, value2, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hpm_user_account
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hpm_user_account
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 02 11:27:06 ICT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}