package com.example.demo.mybatis.model;

import java.util.Date;

public class UserAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.user_name
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.password
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.staff_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String staffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.fullname
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.birthday
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.id_card
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String idCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.home_phone
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String homePhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.mobile_phone
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String mobilePhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.address
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.email
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.role_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.position_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Long positionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.department_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Long departmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.signature_path
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String signaturePath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.signature_pass
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String signaturePass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.doctor_type
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Boolean doctorType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.allow_remote_access
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Boolean allowRemoteAccess;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.is_lock
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Boolean isLock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.user_type
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Boolean userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.is_partner
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Boolean isPartner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.headquarter_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Long headquarterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.headquarter_list
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String headquarterList;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.create_by
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.create_date
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.update_by
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private String updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hpm_user_account.update_date
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	private Date updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.id
	 * @return  the value of hpm_user_account.id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.id
	 * @param id  the value for hpm_user_account.id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.user_name
	 * @return  the value of hpm_user_account.user_name
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.user_name
	 * @param userName  the value for hpm_user_account.user_name
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.password
	 * @return  the value of hpm_user_account.password
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.password
	 * @param password  the value for hpm_user_account.password
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.staff_id
	 * @return  the value of hpm_user_account.staff_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.staff_id
	 * @param staffId  the value for hpm_user_account.staff_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.fullname
	 * @return  the value of hpm_user_account.fullname
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.fullname
	 * @param fullname  the value for hpm_user_account.fullname
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.birthday
	 * @return  the value of hpm_user_account.birthday
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.birthday
	 * @param birthday  the value for hpm_user_account.birthday
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.id_card
	 * @return  the value of hpm_user_account.id_card
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getIdCard() {
		return idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.id_card
	 * @param idCard  the value for hpm_user_account.id_card
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.home_phone
	 * @return  the value of hpm_user_account.home_phone
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getHomePhone() {
		return homePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.home_phone
	 * @param homePhone  the value for hpm_user_account.home_phone
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.mobile_phone
	 * @return  the value of hpm_user_account.mobile_phone
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getMobilePhone() {
		return mobilePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.mobile_phone
	 * @param mobilePhone  the value for hpm_user_account.mobile_phone
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.address
	 * @return  the value of hpm_user_account.address
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.address
	 * @param address  the value for hpm_user_account.address
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.email
	 * @return  the value of hpm_user_account.email
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.email
	 * @param email  the value for hpm_user_account.email
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.role_id
	 * @return  the value of hpm_user_account.role_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.role_id
	 * @param roleId  the value for hpm_user_account.role_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.position_id
	 * @return  the value of hpm_user_account.position_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Long getPositionId() {
		return positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.position_id
	 * @param positionId  the value for hpm_user_account.position_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setPositionId(Long positionId) {
		this.positionId = positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.department_id
	 * @return  the value of hpm_user_account.department_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Long getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.department_id
	 * @param departmentId  the value for hpm_user_account.department_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.signature_path
	 * @return  the value of hpm_user_account.signature_path
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getSignaturePath() {
		return signaturePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.signature_path
	 * @param signaturePath  the value for hpm_user_account.signature_path
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setSignaturePath(String signaturePath) {
		this.signaturePath = signaturePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.signature_pass
	 * @return  the value of hpm_user_account.signature_pass
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getSignaturePass() {
		return signaturePass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.signature_pass
	 * @param signaturePass  the value for hpm_user_account.signature_pass
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setSignaturePass(String signaturePass) {
		this.signaturePass = signaturePass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.doctor_type
	 * @return  the value of hpm_user_account.doctor_type
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Boolean getDoctorType() {
		return doctorType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.doctor_type
	 * @param doctorType  the value for hpm_user_account.doctor_type
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setDoctorType(Boolean doctorType) {
		this.doctorType = doctorType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.allow_remote_access
	 * @return  the value of hpm_user_account.allow_remote_access
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Boolean getAllowRemoteAccess() {
		return allowRemoteAccess;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.allow_remote_access
	 * @param allowRemoteAccess  the value for hpm_user_account.allow_remote_access
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setAllowRemoteAccess(Boolean allowRemoteAccess) {
		this.allowRemoteAccess = allowRemoteAccess;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.is_lock
	 * @return  the value of hpm_user_account.is_lock
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Boolean getIsLock() {
		return isLock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.is_lock
	 * @param isLock  the value for hpm_user_account.is_lock
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setIsLock(Boolean isLock) {
		this.isLock = isLock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.user_type
	 * @return  the value of hpm_user_account.user_type
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Boolean getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.user_type
	 * @param userType  the value for hpm_user_account.user_type
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setUserType(Boolean userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.is_partner
	 * @return  the value of hpm_user_account.is_partner
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Boolean getIsPartner() {
		return isPartner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.is_partner
	 * @param isPartner  the value for hpm_user_account.is_partner
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setIsPartner(Boolean isPartner) {
		this.isPartner = isPartner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.headquarter_id
	 * @return  the value of hpm_user_account.headquarter_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Long getHeadquarterId() {
		return headquarterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.headquarter_id
	 * @param headquarterId  the value for hpm_user_account.headquarter_id
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setHeadquarterId(Long headquarterId) {
		this.headquarterId = headquarterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.headquarter_list
	 * @return  the value of hpm_user_account.headquarter_list
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getHeadquarterList() {
		return headquarterList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.headquarter_list
	 * @param headquarterList  the value for hpm_user_account.headquarter_list
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setHeadquarterList(String headquarterList) {
		this.headquarterList = headquarterList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.create_by
	 * @return  the value of hpm_user_account.create_by
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.create_by
	 * @param createBy  the value for hpm_user_account.create_by
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.create_date
	 * @return  the value of hpm_user_account.create_date
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.create_date
	 * @param createDate  the value for hpm_user_account.create_date
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.update_by
	 * @return  the value of hpm_user_account.update_by
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.update_by
	 * @param updateBy  the value for hpm_user_account.update_by
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hpm_user_account.update_date
	 * @return  the value of hpm_user_account.update_date
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hpm_user_account.update_date
	 * @param updateDate  the value for hpm_user_account.update_date
	 * @mbg.generated  Tue Apr 02 11:27:06 ICT 2024
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
}